[package]
name = "bevy_mod_chroma_request_lib"
version = "0.1.0"
edition = "2021"
description = "Request lib for bevy_mod_chroma"
keywords = [ "game", "gamedev", "bevy", "razer", "chroma" ]
repository = "https://github.com/datael/bevy_mod_chroma/crates/bevy_mod_chroma_request_lib"
rust-version = "1.69.0"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes.workspace = true
serde_json.workspace = true
serde.workspace = true
reqwest.workspace = true
crossbeam-channel.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
bevy.workspace = true

[dev-dependencies]
bevy.workspace = true
