[package]
name = "bevy_mod_chroma_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_mod_chroma_request_lib = { path = "../bevy_mod_chroma_request_lib" }

bytes.workspace = true
serde_json.workspace = true
serde.workspace = true
reqwest.workspace = true
crossbeam-channel.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
bevy.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
bevy.workspace = true

[dev-dependencies]
bevy.workspace = true
